version: '2.3'
services:
  # service:
  #   build: ./
  #   restart: always
  #   ports:
  #     - '1935:1935'
  #     - '8000:8000'
  #   user: '1000'

  # docker run illuspas/node-media-server -p 1939 8000
  #  az container create --resource-group test --name mycontainer --image illuspas/node-media-server --dns-name-label test-video-stream --ports 1935 8000

  ffmpeg:
    # depends_on:
    #   - 'service'
    image: linuxserver/ffmpeg
    volumes:
      - ./test_data:/work
    command: ' -stream_loop -1 -i /work/test.mp4 -c:v libx264 -preset veryfast -maxrate 6000k -bufsize 100000k -pix_fmt yuv420p -g 50 -fflags +genpts  -f flv rtmp://80.158.39.54:30036/live/car-cloudhub'
